from colorama import Fore,Back,Style

print(Fore.GREEN + Style.BRIGHT + "MAD LIBS")
print(Fore.BLUE+"Welcome to Mad Libs! What's your name?")
name = input(Fore.RESET + "")
print(Fore.BLUE + "Hi "+name+"! Lets jump into this...\n")

adj1 = input(Fore.CYAN + "Please enter an adjective\n")
adj2 = input(Fore.CYAN + "Please enter an adjective\n")
noun1 = input(Fore.CYAN + "Please enter a noun\n")
noun2 = input(Fore.CYAN + "Please enter a noun\n")
pl_noun1 = input(Fore.CYAN + "Please enter a plural noun\n")
game = input(Fore.CYAN + "Please enter the name of a game\n")
pl_noun2 = input(Fore.CYAN + "Please enter a plural noun\n")
ing1 = input(Fore.CYAN + "Please enter a verb ending in 'ing'\n")
ing2 = input(Fore.CYAN + "Please enter a verb ending in 'ing'\n")
pl_noun3 = input(Fore.CYAN + "Please enter an adjective\n")
ing3 = input(Fore.CYAN +"Please enter a verb ending in 'ing'\n")
noun3 = input(Fore.CYAN + "Please enter a noun\n")
plant = input(Fore.CYAN + "Please enter a plant species\n")
body_part = input(Fore.CYAN + "Please enter a body part\n")
place = input(Fore.CYAN + "Please enter a place\n")
ing4= input(Fore.CYAN + "Please enter a verb ending in 'ing'\n")
adj3 = input(Fore.CYAN + "Please enter an adjective\n")
num = input(Fore.CYAN + "Please enter a number\n")
pl_noun4 = input(Fore.CYAN + "Please enter a plural noun\n")
print(Fore.RED + "-------------------------------------")
print(Fore.BLUE + "And we're done! Let's get into the passage now\n")
print(Fore.RESET + "A vacation is when you take a trip to some " + Fore.GREEN + adj1 + Fore.RESET + " place with your " + Fore.GREEN + adj2 + Fore.RESET + " family. Usually you go to some place that is near a/an " + Fore.GREEN + noun1 + Fore.RESET + " or up on a/an " + Fore.GREEN + noun2 + Fore.RESET + ". A good vacation place is one where you can ride " + Fore.GREEN + pl_noun1 + Fore.RESET + " or play " + Fore.GREEN + game + Fore.RESET + "  or go hunting for " + Fore.GREEN + pl_noun2 + Fore.RESET + " to spend my time " + Fore.GREEN + ing1 + Fore.RESET + "  or " + Fore.GREEN + ing2+ Fore.RESET + ". When parents go on a vacation, they spend their time eating three " + Fore.GREEN + pl_noun3 + Fore.RESET + " a day, and fathers play golf, and mothers sit around " + Fore.GREEN + ing3 + Fore.RESET + ". Last summer, my little brother fell in a/an " + Fore.GREEN + noun3 + Fore.RESET + "  and got poison " + Fore.GREEN + plant + Fore.RESET + " all over his " + Fore.GREEN + body_part + Fore.RESET + ". My family is going to go to (the) " + Fore.GREEN + place + Fore.RESET + ", and I will practice " + Fore.GREEN + ing4 + Fore.RESET + ". Parents need vacations more than kids because parents are always very " + Fore.GREEN + adj3 + Fore.RESET + " and because they have to work " + Fore.GREEN + num + Fore.RESET + " hours every day all year making enough " + Fore.GREEN + pl_noun4 + Fore.RESET + " to pay for the vacation.")
print(Fore.RED + "-------------------------------------\n")
print(Fore.RESET + "Thanks for playing Mad Libs!")
